runtime: python39
service: default
handlers:
  - url: /static
    static_dir: static



default_expiration: "5m"
env_variables:
  ENV: 'GCLOUD'
  BUCKET: 'cmj-stats.appspot.com'
  USERNAME: 'NGP'
  PASSWORD: '$2b$12$0diwFWRaGE59uTEguOf64erwBClGUZ8Wz8ddkeK2yHmeYl6Gtwvxq'
  SECRET_KEY: '\x98\x85\x1fp_\xab\x17\xdd\x11\xb7'
